spring:
  # 연결할 데이터베이스 정보
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpalearn
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug